public static class InputEvent
{
    // Player
    public const string PLAYER_HORIZONTAL_INPUT = "PLAYER_HORIZONTAL_INPUT";
    public const string PLAYER_VERTICAL_INPUT = "PLAYER_VERTICAL_INPUT";
    public const string PLAYER_JUMP_INPUT = "PLAYER_JUMP_INPUT";
    public const string PLAYER_ATTACK_INPUT = "PLAYER_ATTACK_INPUT";
    public const string PLAYER_RELOAD_INPUT = "PLAYER_RELOAD_INPUT";
    public const string PLAYER_DASH_INPUT = "PLAYER_DASH_INPUT";
    public const string PLAYER_CROUCH_INPUT = "PLAYER_CROUCH_INPUT";
    public const string PLAYER_CHANGE_GUN_INPUT = "PLAYER_CHANGE_GUN_INPUT";
    public const string PLAYER_CAMERA_HORIZONTAL_INPUT = "PLAYER_CAMERA_HORIZONTAL_INPUT";
    public const string PLAYER_CAMERA_VERTICAL_INPUT = "PLAYER_CAMERA_VERTICAL_INPUT";

    // Drone
    public const string DRONE_HORIZONTAL_INPUT = "DRONE_HORIZONTAL_INPUT";
    public const string DRONE_VERTICAL_INPUT = "DRONE_VERTICAL_INPUT";
    public const string DRONE_UP_INPUT = "DRONE_UP_INPUT";
    public const string DRONE_ATTACK_INPUT = "DRONE_ATTACK_INPUT";
    public const string DRONE_CAMERA_HORIZONTAL_INPUT = "DRONE_CAMERA_HORIZONTAL_INPUT";

    // Vehicle
    public const string VEHICLE_HORIZONTAL_INPUT = "VEHICLE_HORIZONTAL_INPUT";
    public const string VEHICLE_VERTICAL_INPUT = "VEHICLE_VERTICAL_INPUT";
    public const string VEHICLE_CAMERA_HORIZONTAL_INPUT = "VEHICLE_CAMERA_HORIZONTAL_INPUT";
    public const string VEHICLE_CAMERA_VERTICAL_INPUT = "VEHICLE_CAMERA_VERTICAL_INPUT";
    public const string VEHICLE_ENTER_EXIT_INPUT = "VEHICLE_ENTER_EXIT_INPUT";
    public const string VECHILE_RADAR_SWITCH_INPUT = "VECHILE_RADAR_SWITCH_INPUT";
    public const string VECHILE_EMP_USE_INPUT = "VECHILE_EMP_USE_INPUT";
    public const string VECHILE_ELERTIC_INTERFERENCE_INPUT = "VECHILE_ELERTIC_INTERFERENCE_INPUT";

    // Game
    public const string GAME_PAUSE_INPUT = "GAME_PAUSE_INPUT";
    public const string OBSERVER_MODE_INPUT = "OBSERVER_MODE_INPUT";
}