//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_legacy : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean left_axis0_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis0_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_axis0_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis0_touch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 left_axis0_value
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis0_value;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_axis1_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis1_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_axis1_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis1_touch;
            }
        }
        
        public virtual SteamVR_Action_Single left_axis1_value
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis1_value;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_axis2_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis2_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_axis2_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis2_touch;
            }
        }
        
        public virtual SteamVR_Action_Single left_axis2_value1
        {
            get
            {
                return SteamVR_Actions.legacy_left_axis2_value1;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_grip_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_grip_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_grip_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_grip_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_a_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_a_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_a_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_a_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_applicationmenu_press
        {
            get
            {
                return SteamVR_Actions.legacy_left_applicationmenu_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_applicationmenu_touch
        {
            get
            {
                return SteamVR_Actions.legacy_left_applicationmenu_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis0_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis0_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis0_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis0_touch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 right_axis0_value
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis0_value;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis1_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis1_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis1_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis1_touch;
            }
        }
        
        public virtual SteamVR_Action_Single right_axis1_value
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis1_value;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis2_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis2_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_axis2_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis2_touch;
            }
        }
        
        public virtual SteamVR_Action_Single right_axis2_value1
        {
            get
            {
                return SteamVR_Actions.legacy_right_axis2_value1;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_grip_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_grip_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_grip_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_grip_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_a_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_a_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_a_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_a_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_applicationmenu_press
        {
            get
            {
                return SteamVR_Actions.legacy_right_applicationmenu_press;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_applicationmenu_touch
        {
            get
            {
                return SteamVR_Actions.legacy_right_applicationmenu_touch;
            }
        }
    }
}
